[book]
authors = ["kuanhsiaokuo"]
description = "ä»¥rustä¸ºä¾‹åˆ†äº«å­¦ä¹ ç¼–ç¨‹å¸¸è€ƒè™‘çš„æ–¹æ–¹é¢é¢"
language = "cn"
multilingual = false
src = "src"
title = "Programming Anatomy In Rust ğŸ¦€"

[output.html]
theme = "mytheme"
default-theme = "rust"
git-repository-url = "https://github.com/KuanHsiaoKuo/programming_anatomy_in_rust.git"
git-repository-icon = "fa-rust"
additional-js = ["assets/mermaid/mermaid.min.js", "assets/mermaid/mermaid-init.js", "assets/smart-anchor.js", "assets/pagetoc/sidebar.js"]
additional-css = ["assets/pagetoc/pagetoc_style.css", "assets/css/mdbook-admonish.css"]
mathjax-support = true


[output.html.playground]
editable = true
copy-js = true

[output.html.fold]
enable = false
level = 0

# Enables the `mdbook-mermaid` preprocessor
[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.puml]
command = "mdbook-puml"

# Enables the `mdbook-checklist` preprocessor
[preprocessor.checklist]
title = "å¾…å®Œå–„: "

# Enables the `mdbook-admonish` preprocessor
[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "2.0.0" # do not edit: managed by `mdbook-admonish install`